Add-convert-to-var
BQSKit/bqskit pull request #161
Opened 2023-07-26 21:51 UTC by alonkukl

Adding the convert to variable untry pass
Adding test to that pass and also to the toU3 pass

2023-07-26 23:41 UTC, edyounis requested changes

2023-07-26 23:41 UTC, edyounis commented on bqskit/passes/util/converttou3.py
> +        self.convert_all_single_qubit_gates = convert_all_single_qubit_gates
Need documentation here

2023-07-26 23:41 UTC, edyounis commented on bqskit/passes/util/converttovar.py
> +"""This module implements the ToU3Pass."""
Incorrect module docstring

2023-07-26 23:41 UTC, edyounis commented on bqskit/passes/util/converttovar.py
> +        self.convert_all_single_qudit_gates = convert_all_single_qudit_gates
Need documentation

2023-07-26 23:41 UTC, edyounis commented on tests/passes/util/test_to_u3.py
> +    assert dist <= 1e-7  # Is this good enough??
Yes

2023-07-26 23:57 UTC, alonkukl commented on bqskit/passes/util/converttou3.py
> +        self.convert_all_single_qubit_gates = convert_all_single_qubit_gates
Added and pushed

2023-07-26 23:57 UTC, alonkukl commented on bqskit/passes/util/converttovar.py
> +"""This module implements the ToU3Pass."""
Fixed it

2023-07-26 23:57 UTC, alonkukl commented on bqskit/passes/util/converttovar.py
> +        self.convert_all_single_qudit_gates = convert_all_single_qudit_gates
Added and pushed

2023-07-27 00:44 UTC, edyounis approved these changes

2023-08-07 14:51 UTC, merged