Hybrid topology
BQSKit/bqskit pull request #32
Opened 2021-06-11 01:14 UTC by mtweiden

Changed the `gen_successors` function to use topology. Still need to figure out how to take `MachineModel`s and split them into subtopologies.

2021-06-12 18:58 UTC, ethanhs commented
Maybe this PR should target the `iterative-reoptimization` branch as a base branch? Not sure how you want to handle that @edyounis . It seems that it would be easier to review this if it didn't have those changes as well.

2021-06-16 19:28 UTC, mtweiden commented
I've changed the target branch to `iterative-reoptimization` and fixed some pre-commit issues. Those that remain have to do with the `lang` files. I plan to make a few more commits to this PR that will add the ability to save checkpoints/intermediate results from synthesis.

2021-06-17 01:15 UTC, ethanhs commented
Excellent! Checkpointing is very useful

2021-06-18 00:07 UTC, mtweiden commented
Okay, I think this branch is ready to be merged with iterative-reoptimization if there are no more changes that y'all think need to happen.

2021-07-08 16:37 UTC, edyounis requested changes
It seems that you are merging the native code PR into it as well. We should chat to figure out these branches before we merge this in. Otherwise, good work, just some small changes requested.

Nit: Please remove all `.DS_Store` files

2021-07-08 17:17 UTC, ethanhs commented on .gitignore
> +scratch/
You can always add a user specific ignore to avoid committing this folder if you wish: https://stackoverflow.com/a/5724499

2021-07-14 13:53 UTC, mtweiden commented on bqskit/ir/circuit.py
> +        HalfWire = tuple[CircuitPoint, str]  # type: ignore
These were added because my interpreter doesn't like ` = tuple[~~]`. Is it okay if I change it to ` : tuple[~~]` instead?

2021-07-14 13:55 UTC, mtweiden commented on bqskit/compiler/passes/synthesispass.py
> +                error = new_utry.get_distance_from(old_utry)
Should I change this to `error = x**2` then?

2021-07-14 13:57 UTC, mtweiden commented on bqskit/compiler/passes/synthesispass.py
> +        f.write(OPENQASM2Language().encode(circuit_copy))
I'm mostly using `SaveIntermediatePass` in `bqskit/compiler/passes/util/intermediate.py`, but that should probably get looked at again as well.

2021-07-14 15:19 UTC, edyounis commented on bqskit/compiler/passes/synthesispass.py
> +        f.write(OPENQASM2Language().encode(circuit_copy))
Yeah, then this is fine for now. Can you stick a TODO in there for now?

2021-07-14 15:20 UTC, edyounis commented on bqskit/ir/circuit.py
> +        HalfWire = tuple[CircuitPoint, str]  # type: ignore
I think, you just need to pull. Let's chat today if you have some time.

2021-07-14 15:21 UTC, edyounis commented on bqskit/compiler/passes/synthesispass.py
> +                error = new_utry.get_distance_from(old_utry)
No, it's a bit more than that. We can discuss this over slack or zoom. I'll send you a slack message.

2021-07-14 16:18 UTC, merged